# Generated by Django 4.2.7 on 2023-12-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager')], default='customer', max_length=10, null=True, verbose_name='User Type'),
        ),
    ]
