# Generated by Django 4.2.7 on 2023-12-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.TextField(blank=True, max_length=10, verbose_name='First Name'),
        ),
    ]
