# Generated by Django 4.2.7 on 2023-12-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_user_type_alter_profile_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('manager', 'Manager')], default='customer', max_length=10, null=True, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.TextField(blank=True, max_length=10, verbose_name='Last Name'),
        ),
    ]
