# Generated by Django 4.2.7 on 2023-11-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
