# Generated by Django 4.2.7 on 2023-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
