# Generated by Django 4.2.7 on 2023-12-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_biography_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
