# Generated by Django 4.2.7 on 2023-12-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_available'),
        ('shop', '0004_alter_product_image_alter_product_stock'),
    ]

    operations = [
    ]
