# Generated by Django 4.2.7 on 2023-12-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['date_added'], 'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
    ]
